### ISSUE TITLE
Data is lost during json to csv conversion

### ISSUE THREAD

**Issue by koleosfuscus** [gedankenstuecke/activity_tracking#1]
Hi,  I found the line `df_merged = pd.merge(df_merged, df, on='date')` is losing data when there is no data from some of the fitbit variables. Outer join must be specified to catch all days: df_merged = pd.merge(df_merged, df, on='date', how='outer')

**Comment by gedankenstuecke** [comment]
Yes, that worked. Thanks for the input. I fixed it in the code! 👍
